version: '3'
services:
  python:
    build: .
    working_dir: '/myapp'
    tty: true
    volumes:
      - .:/myapp
      - virtualenvs:/root/.cache/pypoetry/virtualenvs
      
volumes:
  virtualenvs:
    driver: local
